# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

coverage:
  status:
    project:
      default:
        # this project is not currently at the desired target of 85%
        # target: 85%
        target: 74%
    patch:
      default:
        target: 85%
        only_pulls: true

ignore:
  - "test/integration/**/*"
