// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hyperledger/fabric-sdk-go/pkg/fabsdk/api (interfaces: CoreProviders,SvcProviders,Providers,CoreProviderFactory,ServiceProviderFactory,OrgClientFactory,SessionClientFactory)

package mock_api

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apiconfig "github.com/hyperledger/fabric-sdk-go/api/apiconfig"
	apicore "github.com/hyperledger/fabric-sdk-go/api/apicore"
	apicryptosuite "github.com/hyperledger/fabric-sdk-go/api/apicryptosuite"
	apifabclient "github.com/hyperledger/fabric-sdk-go/api/apifabclient"
	chclient "github.com/hyperledger/fabric-sdk-go/api/apitxn/chclient"
	chmgmtclient "github.com/hyperledger/fabric-sdk-go/api/apitxn/chmgmtclient"
	resmgmtclient "github.com/hyperledger/fabric-sdk-go/api/apitxn/resmgmtclient"
	api "github.com/hyperledger/fabric-sdk-go/pkg/fabsdk/api"
)

// MockCoreProviders is a mock of CoreProviders interface
type MockCoreProviders struct {
	ctrl     *gomock.Controller
	recorder *MockCoreProvidersMockRecorder
}

// MockCoreProvidersMockRecorder is the mock recorder for MockCoreProviders
type MockCoreProvidersMockRecorder struct {
	mock *MockCoreProviders
}

// NewMockCoreProviders creates a new mock instance
func NewMockCoreProviders(ctrl *gomock.Controller) *MockCoreProviders {
	mock := &MockCoreProviders{ctrl: ctrl}
	mock.recorder = &MockCoreProvidersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCoreProviders) EXPECT() *MockCoreProvidersMockRecorder {
	return _m.recorder
}

// Config mocks base method
func (_m *MockCoreProviders) Config() apiconfig.Config {
	ret := _m.ctrl.Call(_m, "Config")
	ret0, _ := ret[0].(apiconfig.Config)
	return ret0
}

// Config indicates an expected call of Config
func (_mr *MockCoreProvidersMockRecorder) Config() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Config", reflect.TypeOf((*MockCoreProviders)(nil).Config))
}

// CryptoSuite mocks base method
func (_m *MockCoreProviders) CryptoSuite() apicryptosuite.CryptoSuite {
	ret := _m.ctrl.Call(_m, "CryptoSuite")
	ret0, _ := ret[0].(apicryptosuite.CryptoSuite)
	return ret0
}

// CryptoSuite indicates an expected call of CryptoSuite
func (_mr *MockCoreProvidersMockRecorder) CryptoSuite() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CryptoSuite", reflect.TypeOf((*MockCoreProviders)(nil).CryptoSuite))
}

// FabricProvider mocks base method
func (_m *MockCoreProviders) FabricProvider() apicore.FabricProvider {
	ret := _m.ctrl.Call(_m, "FabricProvider")
	ret0, _ := ret[0].(apicore.FabricProvider)
	return ret0
}

// FabricProvider indicates an expected call of FabricProvider
func (_mr *MockCoreProvidersMockRecorder) FabricProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FabricProvider", reflect.TypeOf((*MockCoreProviders)(nil).FabricProvider))
}

// SigningManager mocks base method
func (_m *MockCoreProviders) SigningManager() apifabclient.SigningManager {
	ret := _m.ctrl.Call(_m, "SigningManager")
	ret0, _ := ret[0].(apifabclient.SigningManager)
	return ret0
}

// SigningManager indicates an expected call of SigningManager
func (_mr *MockCoreProvidersMockRecorder) SigningManager() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SigningManager", reflect.TypeOf((*MockCoreProviders)(nil).SigningManager))
}

// StateStore mocks base method
func (_m *MockCoreProviders) StateStore() apifabclient.KeyValueStore {
	ret := _m.ctrl.Call(_m, "StateStore")
	ret0, _ := ret[0].(apifabclient.KeyValueStore)
	return ret0
}

// StateStore indicates an expected call of StateStore
func (_mr *MockCoreProvidersMockRecorder) StateStore() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "StateStore", reflect.TypeOf((*MockCoreProviders)(nil).StateStore))
}

// MockSvcProviders is a mock of SvcProviders interface
type MockSvcProviders struct {
	ctrl     *gomock.Controller
	recorder *MockSvcProvidersMockRecorder
}

// MockSvcProvidersMockRecorder is the mock recorder for MockSvcProviders
type MockSvcProvidersMockRecorder struct {
	mock *MockSvcProviders
}

// NewMockSvcProviders creates a new mock instance
func NewMockSvcProviders(ctrl *gomock.Controller) *MockSvcProviders {
	mock := &MockSvcProviders{ctrl: ctrl}
	mock.recorder = &MockSvcProvidersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSvcProviders) EXPECT() *MockSvcProvidersMockRecorder {
	return _m.recorder
}

// ChannelProvider mocks base method
func (_m *MockSvcProviders) ChannelProvider() apifabclient.ChannelProvider {
	ret := _m.ctrl.Call(_m, "ChannelProvider")
	ret0, _ := ret[0].(apifabclient.ChannelProvider)
	return ret0
}

// ChannelProvider indicates an expected call of ChannelProvider
func (_mr *MockSvcProvidersMockRecorder) ChannelProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ChannelProvider", reflect.TypeOf((*MockSvcProviders)(nil).ChannelProvider))
}

// DiscoveryProvider mocks base method
func (_m *MockSvcProviders) DiscoveryProvider() apifabclient.DiscoveryProvider {
	ret := _m.ctrl.Call(_m, "DiscoveryProvider")
	ret0, _ := ret[0].(apifabclient.DiscoveryProvider)
	return ret0
}

// DiscoveryProvider indicates an expected call of DiscoveryProvider
func (_mr *MockSvcProvidersMockRecorder) DiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DiscoveryProvider", reflect.TypeOf((*MockSvcProviders)(nil).DiscoveryProvider))
}

// SelectionProvider mocks base method
func (_m *MockSvcProviders) SelectionProvider() apifabclient.SelectionProvider {
	ret := _m.ctrl.Call(_m, "SelectionProvider")
	ret0, _ := ret[0].(apifabclient.SelectionProvider)
	return ret0
}

// SelectionProvider indicates an expected call of SelectionProvider
func (_mr *MockSvcProvidersMockRecorder) SelectionProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectionProvider", reflect.TypeOf((*MockSvcProviders)(nil).SelectionProvider))
}

// MockProviders is a mock of Providers interface
type MockProviders struct {
	ctrl     *gomock.Controller
	recorder *MockProvidersMockRecorder
}

// MockProvidersMockRecorder is the mock recorder for MockProviders
type MockProvidersMockRecorder struct {
	mock *MockProviders
}

// NewMockProviders creates a new mock instance
func NewMockProviders(ctrl *gomock.Controller) *MockProviders {
	mock := &MockProviders{ctrl: ctrl}
	mock.recorder = &MockProvidersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockProviders) EXPECT() *MockProvidersMockRecorder {
	return _m.recorder
}

// ChannelProvider mocks base method
func (_m *MockProviders) ChannelProvider() apifabclient.ChannelProvider {
	ret := _m.ctrl.Call(_m, "ChannelProvider")
	ret0, _ := ret[0].(apifabclient.ChannelProvider)
	return ret0
}

// ChannelProvider indicates an expected call of ChannelProvider
func (_mr *MockProvidersMockRecorder) ChannelProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ChannelProvider", reflect.TypeOf((*MockProviders)(nil).ChannelProvider))
}

// Config mocks base method
func (_m *MockProviders) Config() apiconfig.Config {
	ret := _m.ctrl.Call(_m, "Config")
	ret0, _ := ret[0].(apiconfig.Config)
	return ret0
}

// Config indicates an expected call of Config
func (_mr *MockProvidersMockRecorder) Config() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Config", reflect.TypeOf((*MockProviders)(nil).Config))
}

// CryptoSuite mocks base method
func (_m *MockProviders) CryptoSuite() apicryptosuite.CryptoSuite {
	ret := _m.ctrl.Call(_m, "CryptoSuite")
	ret0, _ := ret[0].(apicryptosuite.CryptoSuite)
	return ret0
}

// CryptoSuite indicates an expected call of CryptoSuite
func (_mr *MockProvidersMockRecorder) CryptoSuite() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CryptoSuite", reflect.TypeOf((*MockProviders)(nil).CryptoSuite))
}

// DiscoveryProvider mocks base method
func (_m *MockProviders) DiscoveryProvider() apifabclient.DiscoveryProvider {
	ret := _m.ctrl.Call(_m, "DiscoveryProvider")
	ret0, _ := ret[0].(apifabclient.DiscoveryProvider)
	return ret0
}

// DiscoveryProvider indicates an expected call of DiscoveryProvider
func (_mr *MockProvidersMockRecorder) DiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DiscoveryProvider", reflect.TypeOf((*MockProviders)(nil).DiscoveryProvider))
}

// FabricProvider mocks base method
func (_m *MockProviders) FabricProvider() apicore.FabricProvider {
	ret := _m.ctrl.Call(_m, "FabricProvider")
	ret0, _ := ret[0].(apicore.FabricProvider)
	return ret0
}

// FabricProvider indicates an expected call of FabricProvider
func (_mr *MockProvidersMockRecorder) FabricProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FabricProvider", reflect.TypeOf((*MockProviders)(nil).FabricProvider))
}

// SelectionProvider mocks base method
func (_m *MockProviders) SelectionProvider() apifabclient.SelectionProvider {
	ret := _m.ctrl.Call(_m, "SelectionProvider")
	ret0, _ := ret[0].(apifabclient.SelectionProvider)
	return ret0
}

// SelectionProvider indicates an expected call of SelectionProvider
func (_mr *MockProvidersMockRecorder) SelectionProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectionProvider", reflect.TypeOf((*MockProviders)(nil).SelectionProvider))
}

// SigningManager mocks base method
func (_m *MockProviders) SigningManager() apifabclient.SigningManager {
	ret := _m.ctrl.Call(_m, "SigningManager")
	ret0, _ := ret[0].(apifabclient.SigningManager)
	return ret0
}

// SigningManager indicates an expected call of SigningManager
func (_mr *MockProvidersMockRecorder) SigningManager() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SigningManager", reflect.TypeOf((*MockProviders)(nil).SigningManager))
}

// StateStore mocks base method
func (_m *MockProviders) StateStore() apifabclient.KeyValueStore {
	ret := _m.ctrl.Call(_m, "StateStore")
	ret0, _ := ret[0].(apifabclient.KeyValueStore)
	return ret0
}

// StateStore indicates an expected call of StateStore
func (_mr *MockProvidersMockRecorder) StateStore() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "StateStore", reflect.TypeOf((*MockProviders)(nil).StateStore))
}

// MockCoreProviderFactory is a mock of CoreProviderFactory interface
type MockCoreProviderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCoreProviderFactoryMockRecorder
}

// MockCoreProviderFactoryMockRecorder is the mock recorder for MockCoreProviderFactory
type MockCoreProviderFactoryMockRecorder struct {
	mock *MockCoreProviderFactory
}

// NewMockCoreProviderFactory creates a new mock instance
func NewMockCoreProviderFactory(ctrl *gomock.Controller) *MockCoreProviderFactory {
	mock := &MockCoreProviderFactory{ctrl: ctrl}
	mock.recorder = &MockCoreProviderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCoreProviderFactory) EXPECT() *MockCoreProviderFactoryMockRecorder {
	return _m.recorder
}

// NewCryptoSuiteProvider mocks base method
func (_m *MockCoreProviderFactory) NewCryptoSuiteProvider(_param0 apiconfig.Config) (apicryptosuite.CryptoSuite, error) {
	ret := _m.ctrl.Call(_m, "NewCryptoSuiteProvider", _param0)
	ret0, _ := ret[0].(apicryptosuite.CryptoSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCryptoSuiteProvider indicates an expected call of NewCryptoSuiteProvider
func (_mr *MockCoreProviderFactoryMockRecorder) NewCryptoSuiteProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewCryptoSuiteProvider", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewCryptoSuiteProvider), arg0)
}

// NewFabricProvider mocks base method
func (_m *MockCoreProviderFactory) NewFabricProvider(_param0 apifabclient.ProviderContext) (apicore.FabricProvider, error) {
	ret := _m.ctrl.Call(_m, "NewFabricProvider", _param0)
	ret0, _ := ret[0].(apicore.FabricProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFabricProvider indicates an expected call of NewFabricProvider
func (_mr *MockCoreProviderFactoryMockRecorder) NewFabricProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewFabricProvider", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewFabricProvider), arg0)
}

// NewSigningManager mocks base method
func (_m *MockCoreProviderFactory) NewSigningManager(_param0 apicryptosuite.CryptoSuite, _param1 apiconfig.Config) (apifabclient.SigningManager, error) {
	ret := _m.ctrl.Call(_m, "NewSigningManager", _param0, _param1)
	ret0, _ := ret[0].(apifabclient.SigningManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSigningManager indicates an expected call of NewSigningManager
func (_mr *MockCoreProviderFactoryMockRecorder) NewSigningManager(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewSigningManager", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewSigningManager), arg0, arg1)
}

// NewStateStoreProvider mocks base method
func (_m *MockCoreProviderFactory) NewStateStoreProvider(_param0 apiconfig.Config) (apifabclient.KeyValueStore, error) {
	ret := _m.ctrl.Call(_m, "NewStateStoreProvider", _param0)
	ret0, _ := ret[0].(apifabclient.KeyValueStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewStateStoreProvider indicates an expected call of NewStateStoreProvider
func (_mr *MockCoreProviderFactoryMockRecorder) NewStateStoreProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewStateStoreProvider", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewStateStoreProvider), arg0)
}

// MockServiceProviderFactory is a mock of ServiceProviderFactory interface
type MockServiceProviderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderFactoryMockRecorder
}

// MockServiceProviderFactoryMockRecorder is the mock recorder for MockServiceProviderFactory
type MockServiceProviderFactoryMockRecorder struct {
	mock *MockServiceProviderFactory
}

// NewMockServiceProviderFactory creates a new mock instance
func NewMockServiceProviderFactory(ctrl *gomock.Controller) *MockServiceProviderFactory {
	mock := &MockServiceProviderFactory{ctrl: ctrl}
	mock.recorder = &MockServiceProviderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockServiceProviderFactory) EXPECT() *MockServiceProviderFactoryMockRecorder {
	return _m.recorder
}

// NewDiscoveryProvider mocks base method
func (_m *MockServiceProviderFactory) NewDiscoveryProvider(_param0 apiconfig.Config) (apifabclient.DiscoveryProvider, error) {
	ret := _m.ctrl.Call(_m, "NewDiscoveryProvider", _param0)
	ret0, _ := ret[0].(apifabclient.DiscoveryProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDiscoveryProvider indicates an expected call of NewDiscoveryProvider
func (_mr *MockServiceProviderFactoryMockRecorder) NewDiscoveryProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewDiscoveryProvider", reflect.TypeOf((*MockServiceProviderFactory)(nil).NewDiscoveryProvider), arg0)
}

// NewSelectionProvider mocks base method
func (_m *MockServiceProviderFactory) NewSelectionProvider(_param0 apiconfig.Config) (apifabclient.SelectionProvider, error) {
	ret := _m.ctrl.Call(_m, "NewSelectionProvider", _param0)
	ret0, _ := ret[0].(apifabclient.SelectionProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSelectionProvider indicates an expected call of NewSelectionProvider
func (_mr *MockServiceProviderFactoryMockRecorder) NewSelectionProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewSelectionProvider", reflect.TypeOf((*MockServiceProviderFactory)(nil).NewSelectionProvider), arg0)
}

// MockOrgClientFactory is a mock of OrgClientFactory interface
type MockOrgClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockOrgClientFactoryMockRecorder
}

// MockOrgClientFactoryMockRecorder is the mock recorder for MockOrgClientFactory
type MockOrgClientFactoryMockRecorder struct {
	mock *MockOrgClientFactory
}

// NewMockOrgClientFactory creates a new mock instance
func NewMockOrgClientFactory(ctrl *gomock.Controller) *MockOrgClientFactory {
	mock := &MockOrgClientFactory{ctrl: ctrl}
	mock.recorder = &MockOrgClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockOrgClientFactory) EXPECT() *MockOrgClientFactoryMockRecorder {
	return _m.recorder
}

// NewCredentialManager mocks base method
func (_m *MockOrgClientFactory) NewCredentialManager(_param0 string, _param1 apiconfig.Config, _param2 apicryptosuite.CryptoSuite) (apifabclient.CredentialManager, error) {
	ret := _m.ctrl.Call(_m, "NewCredentialManager", _param0, _param1, _param2)
	ret0, _ := ret[0].(apifabclient.CredentialManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCredentialManager indicates an expected call of NewCredentialManager
func (_mr *MockOrgClientFactoryMockRecorder) NewCredentialManager(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewCredentialManager", reflect.TypeOf((*MockOrgClientFactory)(nil).NewCredentialManager), arg0, arg1, arg2)
}

// MockSessionClientFactory is a mock of SessionClientFactory interface
type MockSessionClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSessionClientFactoryMockRecorder
}

// MockSessionClientFactoryMockRecorder is the mock recorder for MockSessionClientFactory
type MockSessionClientFactoryMockRecorder struct {
	mock *MockSessionClientFactory
}

// NewMockSessionClientFactory creates a new mock instance
func NewMockSessionClientFactory(ctrl *gomock.Controller) *MockSessionClientFactory {
	mock := &MockSessionClientFactory{ctrl: ctrl}
	mock.recorder = &MockSessionClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSessionClientFactory) EXPECT() *MockSessionClientFactoryMockRecorder {
	return _m.recorder
}

// NewChannelClient mocks base method
func (_m *MockSessionClientFactory) NewChannelClient(_param0 api.Providers, _param1 api.SessionContext, _param2 string, _param3 apifabclient.TargetFilter) (chclient.ChannelClient, error) {
	ret := _m.ctrl.Call(_m, "NewChannelClient", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(chclient.ChannelClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChannelClient indicates an expected call of NewChannelClient
func (_mr *MockSessionClientFactoryMockRecorder) NewChannelClient(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewChannelClient", reflect.TypeOf((*MockSessionClientFactory)(nil).NewChannelClient), arg0, arg1, arg2, arg3)
}

// NewChannelMgmtClient mocks base method
func (_m *MockSessionClientFactory) NewChannelMgmtClient(_param0 api.Providers, _param1 api.SessionContext) (chmgmtclient.ChannelMgmtClient, error) {
	ret := _m.ctrl.Call(_m, "NewChannelMgmtClient", _param0, _param1)
	ret0, _ := ret[0].(chmgmtclient.ChannelMgmtClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChannelMgmtClient indicates an expected call of NewChannelMgmtClient
func (_mr *MockSessionClientFactoryMockRecorder) NewChannelMgmtClient(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewChannelMgmtClient", reflect.TypeOf((*MockSessionClientFactory)(nil).NewChannelMgmtClient), arg0, arg1)
}

// NewResourceMgmtClient mocks base method
func (_m *MockSessionClientFactory) NewResourceMgmtClient(_param0 api.Providers, _param1 api.SessionContext, _param2 resmgmtclient.TargetFilter) (resmgmtclient.ResourceMgmtClient, error) {
	ret := _m.ctrl.Call(_m, "NewResourceMgmtClient", _param0, _param1, _param2)
	ret0, _ := ret[0].(resmgmtclient.ResourceMgmtClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewResourceMgmtClient indicates an expected call of NewResourceMgmtClient
func (_mr *MockSessionClientFactoryMockRecorder) NewResourceMgmtClient(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewResourceMgmtClient", reflect.TypeOf((*MockSessionClientFactory)(nil).NewResourceMgmtClient), arg0, arg1, arg2)
}
