// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hyperledger/fabric-sdk-go/pkg/fabsdk/api (interfaces: SDK,CoreProviderFactory,ServiceProviderFactory,OrgClientFactory,SessionClientFactory)

package mock_api

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apiconfig "github.com/hyperledger/fabric-sdk-go/api/apiconfig"
	apicore "github.com/hyperledger/fabric-sdk-go/api/apicore"
	apicryptosuite "github.com/hyperledger/fabric-sdk-go/api/apicryptosuite"
	apifabclient "github.com/hyperledger/fabric-sdk-go/api/apifabclient"
	apitxn "github.com/hyperledger/fabric-sdk-go/api/apitxn"
	chmgmtclient "github.com/hyperledger/fabric-sdk-go/api/apitxn/chmgmtclient"
	resmgmtclient "github.com/hyperledger/fabric-sdk-go/api/apitxn/resmgmtclient"
	api "github.com/hyperledger/fabric-sdk-go/pkg/fabsdk/api"
)

// MockSDK is a mock of SDK interface
type MockSDK struct {
	ctrl     *gomock.Controller
	recorder *MockSDKMockRecorder
}

// MockSDKMockRecorder is the mock recorder for MockSDK
type MockSDKMockRecorder struct {
	mock *MockSDK
}

// NewMockSDK creates a new mock instance
func NewMockSDK(ctrl *gomock.Controller) *MockSDK {
	mock := &MockSDK{ctrl: ctrl}
	mock.recorder = &MockSDKMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSDK) EXPECT() *MockSDKMockRecorder {
	return _m.recorder
}

// ConfigProvider mocks base method
func (_m *MockSDK) ConfigProvider() apiconfig.Config {
	ret := _m.ctrl.Call(_m, "ConfigProvider")
	ret0, _ := ret[0].(apiconfig.Config)
	return ret0
}

// ConfigProvider indicates an expected call of ConfigProvider
func (_mr *MockSDKMockRecorder) ConfigProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ConfigProvider", reflect.TypeOf((*MockSDK)(nil).ConfigProvider))
}

// CryptoSuiteProvider mocks base method
func (_m *MockSDK) CryptoSuiteProvider() apicryptosuite.CryptoSuite {
	ret := _m.ctrl.Call(_m, "CryptoSuiteProvider")
	ret0, _ := ret[0].(apicryptosuite.CryptoSuite)
	return ret0
}

// CryptoSuiteProvider indicates an expected call of CryptoSuiteProvider
func (_mr *MockSDKMockRecorder) CryptoSuiteProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CryptoSuiteProvider", reflect.TypeOf((*MockSDK)(nil).CryptoSuiteProvider))
}

// DiscoveryProvider mocks base method
func (_m *MockSDK) DiscoveryProvider() apifabclient.DiscoveryProvider {
	ret := _m.ctrl.Call(_m, "DiscoveryProvider")
	ret0, _ := ret[0].(apifabclient.DiscoveryProvider)
	return ret0
}

// DiscoveryProvider indicates an expected call of DiscoveryProvider
func (_mr *MockSDKMockRecorder) DiscoveryProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DiscoveryProvider", reflect.TypeOf((*MockSDK)(nil).DiscoveryProvider))
}

// FabricProvider mocks base method
func (_m *MockSDK) FabricProvider() apicore.FabricProvider {
	ret := _m.ctrl.Call(_m, "FabricProvider")
	ret0, _ := ret[0].(apicore.FabricProvider)
	return ret0
}

// FabricProvider indicates an expected call of FabricProvider
func (_mr *MockSDKMockRecorder) FabricProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "FabricProvider", reflect.TypeOf((*MockSDK)(nil).FabricProvider))
}

// SelectionProvider mocks base method
func (_m *MockSDK) SelectionProvider() apifabclient.SelectionProvider {
	ret := _m.ctrl.Call(_m, "SelectionProvider")
	ret0, _ := ret[0].(apifabclient.SelectionProvider)
	return ret0
}

// SelectionProvider indicates an expected call of SelectionProvider
func (_mr *MockSDKMockRecorder) SelectionProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SelectionProvider", reflect.TypeOf((*MockSDK)(nil).SelectionProvider))
}

// SigningManager mocks base method
func (_m *MockSDK) SigningManager() apifabclient.SigningManager {
	ret := _m.ctrl.Call(_m, "SigningManager")
	ret0, _ := ret[0].(apifabclient.SigningManager)
	return ret0
}

// SigningManager indicates an expected call of SigningManager
func (_mr *MockSDKMockRecorder) SigningManager() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "SigningManager", reflect.TypeOf((*MockSDK)(nil).SigningManager))
}

// StateStoreProvider mocks base method
func (_m *MockSDK) StateStoreProvider() apifabclient.KeyValueStore {
	ret := _m.ctrl.Call(_m, "StateStoreProvider")
	ret0, _ := ret[0].(apifabclient.KeyValueStore)
	return ret0
}

// StateStoreProvider indicates an expected call of StateStoreProvider
func (_mr *MockSDKMockRecorder) StateStoreProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "StateStoreProvider", reflect.TypeOf((*MockSDK)(nil).StateStoreProvider))
}

// MockCoreProviderFactory is a mock of CoreProviderFactory interface
type MockCoreProviderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCoreProviderFactoryMockRecorder
}

// MockCoreProviderFactoryMockRecorder is the mock recorder for MockCoreProviderFactory
type MockCoreProviderFactoryMockRecorder struct {
	mock *MockCoreProviderFactory
}

// NewMockCoreProviderFactory creates a new mock instance
func NewMockCoreProviderFactory(ctrl *gomock.Controller) *MockCoreProviderFactory {
	mock := &MockCoreProviderFactory{ctrl: ctrl}
	mock.recorder = &MockCoreProviderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCoreProviderFactory) EXPECT() *MockCoreProviderFactoryMockRecorder {
	return _m.recorder
}

// NewCryptoSuiteProvider mocks base method
func (_m *MockCoreProviderFactory) NewCryptoSuiteProvider(_param0 apiconfig.Config) (apicryptosuite.CryptoSuite, error) {
	ret := _m.ctrl.Call(_m, "NewCryptoSuiteProvider", _param0)
	ret0, _ := ret[0].(apicryptosuite.CryptoSuite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCryptoSuiteProvider indicates an expected call of NewCryptoSuiteProvider
func (_mr *MockCoreProviderFactoryMockRecorder) NewCryptoSuiteProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewCryptoSuiteProvider", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewCryptoSuiteProvider), arg0)
}

// NewFabricProvider mocks base method
func (_m *MockCoreProviderFactory) NewFabricProvider(_param0 apiconfig.Config, _param1 apifabclient.KeyValueStore, _param2 apicryptosuite.CryptoSuite, _param3 apifabclient.SigningManager) (apicore.FabricProvider, error) {
	ret := _m.ctrl.Call(_m, "NewFabricProvider", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(apicore.FabricProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFabricProvider indicates an expected call of NewFabricProvider
func (_mr *MockCoreProviderFactoryMockRecorder) NewFabricProvider(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewFabricProvider", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewFabricProvider), arg0, arg1, arg2, arg3)
}

// NewSigningManager mocks base method
func (_m *MockCoreProviderFactory) NewSigningManager(_param0 apicryptosuite.CryptoSuite, _param1 apiconfig.Config) (apifabclient.SigningManager, error) {
	ret := _m.ctrl.Call(_m, "NewSigningManager", _param0, _param1)
	ret0, _ := ret[0].(apifabclient.SigningManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSigningManager indicates an expected call of NewSigningManager
func (_mr *MockCoreProviderFactoryMockRecorder) NewSigningManager(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewSigningManager", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewSigningManager), arg0, arg1)
}

// NewStateStoreProvider mocks base method
func (_m *MockCoreProviderFactory) NewStateStoreProvider(_param0 apiconfig.Config) (apifabclient.KeyValueStore, error) {
	ret := _m.ctrl.Call(_m, "NewStateStoreProvider", _param0)
	ret0, _ := ret[0].(apifabclient.KeyValueStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewStateStoreProvider indicates an expected call of NewStateStoreProvider
func (_mr *MockCoreProviderFactoryMockRecorder) NewStateStoreProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewStateStoreProvider", reflect.TypeOf((*MockCoreProviderFactory)(nil).NewStateStoreProvider), arg0)
}

// MockServiceProviderFactory is a mock of ServiceProviderFactory interface
type MockServiceProviderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderFactoryMockRecorder
}

// MockServiceProviderFactoryMockRecorder is the mock recorder for MockServiceProviderFactory
type MockServiceProviderFactoryMockRecorder struct {
	mock *MockServiceProviderFactory
}

// NewMockServiceProviderFactory creates a new mock instance
func NewMockServiceProviderFactory(ctrl *gomock.Controller) *MockServiceProviderFactory {
	mock := &MockServiceProviderFactory{ctrl: ctrl}
	mock.recorder = &MockServiceProviderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockServiceProviderFactory) EXPECT() *MockServiceProviderFactoryMockRecorder {
	return _m.recorder
}

// NewDiscoveryProvider mocks base method
func (_m *MockServiceProviderFactory) NewDiscoveryProvider(_param0 apiconfig.Config) (apifabclient.DiscoveryProvider, error) {
	ret := _m.ctrl.Call(_m, "NewDiscoveryProvider", _param0)
	ret0, _ := ret[0].(apifabclient.DiscoveryProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDiscoveryProvider indicates an expected call of NewDiscoveryProvider
func (_mr *MockServiceProviderFactoryMockRecorder) NewDiscoveryProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewDiscoveryProvider", reflect.TypeOf((*MockServiceProviderFactory)(nil).NewDiscoveryProvider), arg0)
}

// NewSelectionProvider mocks base method
func (_m *MockServiceProviderFactory) NewSelectionProvider(_param0 apiconfig.Config) (apifabclient.SelectionProvider, error) {
	ret := _m.ctrl.Call(_m, "NewSelectionProvider", _param0)
	ret0, _ := ret[0].(apifabclient.SelectionProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSelectionProvider indicates an expected call of NewSelectionProvider
func (_mr *MockServiceProviderFactoryMockRecorder) NewSelectionProvider(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewSelectionProvider", reflect.TypeOf((*MockServiceProviderFactory)(nil).NewSelectionProvider), arg0)
}

// MockOrgClientFactory is a mock of OrgClientFactory interface
type MockOrgClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockOrgClientFactoryMockRecorder
}

// MockOrgClientFactoryMockRecorder is the mock recorder for MockOrgClientFactory
type MockOrgClientFactoryMockRecorder struct {
	mock *MockOrgClientFactory
}

// NewMockOrgClientFactory creates a new mock instance
func NewMockOrgClientFactory(ctrl *gomock.Controller) *MockOrgClientFactory {
	mock := &MockOrgClientFactory{ctrl: ctrl}
	mock.recorder = &MockOrgClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockOrgClientFactory) EXPECT() *MockOrgClientFactoryMockRecorder {
	return _m.recorder
}

// NewCredentialManager mocks base method
func (_m *MockOrgClientFactory) NewCredentialManager(_param0 string, _param1 apiconfig.Config, _param2 apicryptosuite.CryptoSuite) (apifabclient.CredentialManager, error) {
	ret := _m.ctrl.Call(_m, "NewCredentialManager", _param0, _param1, _param2)
	ret0, _ := ret[0].(apifabclient.CredentialManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCredentialManager indicates an expected call of NewCredentialManager
func (_mr *MockOrgClientFactoryMockRecorder) NewCredentialManager(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewCredentialManager", reflect.TypeOf((*MockOrgClientFactory)(nil).NewCredentialManager), arg0, arg1, arg2)
}

// MockSessionClientFactory is a mock of SessionClientFactory interface
type MockSessionClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSessionClientFactoryMockRecorder
}

// MockSessionClientFactoryMockRecorder is the mock recorder for MockSessionClientFactory
type MockSessionClientFactoryMockRecorder struct {
	mock *MockSessionClientFactory
}

// NewMockSessionClientFactory creates a new mock instance
func NewMockSessionClientFactory(ctrl *gomock.Controller) *MockSessionClientFactory {
	mock := &MockSessionClientFactory{ctrl: ctrl}
	mock.recorder = &MockSessionClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSessionClientFactory) EXPECT() *MockSessionClientFactoryMockRecorder {
	return _m.recorder
}

// NewChannelClient mocks base method
func (_m *MockSessionClientFactory) NewChannelClient(_param0 api.SDK, _param1 api.Session, _param2 apiconfig.Config, _param3 string) (apitxn.ChannelClient, error) {
	ret := _m.ctrl.Call(_m, "NewChannelClient", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(apitxn.ChannelClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChannelClient indicates an expected call of NewChannelClient
func (_mr *MockSessionClientFactoryMockRecorder) NewChannelClient(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewChannelClient", reflect.TypeOf((*MockSessionClientFactory)(nil).NewChannelClient), arg0, arg1, arg2, arg3)
}

// NewChannelMgmtClient mocks base method
func (_m *MockSessionClientFactory) NewChannelMgmtClient(_param0 api.SDK, _param1 api.Session, _param2 apiconfig.Config) (chmgmtclient.ChannelMgmtClient, error) {
	ret := _m.ctrl.Call(_m, "NewChannelMgmtClient", _param0, _param1, _param2)
	ret0, _ := ret[0].(chmgmtclient.ChannelMgmtClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewChannelMgmtClient indicates an expected call of NewChannelMgmtClient
func (_mr *MockSessionClientFactoryMockRecorder) NewChannelMgmtClient(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewChannelMgmtClient", reflect.TypeOf((*MockSessionClientFactory)(nil).NewChannelMgmtClient), arg0, arg1, arg2)
}

// NewResourceMgmtClient mocks base method
func (_m *MockSessionClientFactory) NewResourceMgmtClient(_param0 api.SDK, _param1 api.Session, _param2 apiconfig.Config, _param3 resmgmtclient.TargetFilter) (resmgmtclient.ResourceMgmtClient, error) {
	ret := _m.ctrl.Call(_m, "NewResourceMgmtClient", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(resmgmtclient.ResourceMgmtClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewResourceMgmtClient indicates an expected call of NewResourceMgmtClient
func (_mr *MockSessionClientFactoryMockRecorder) NewResourceMgmtClient(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "NewResourceMgmtClient", reflect.TypeOf((*MockSessionClientFactory)(nil).NewResourceMgmtClient), arg0, arg1, arg2, arg3)
}
